#pragma once
#include "CoreMinimal.h"
#include "TresGimmickHitCountComponentOnTresAccumulationRecoverSignatureDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE(FTresGimmickHitCountComponentOnTresAccumulationRecoverSignature);

