#pragma once
#include "CoreMinimal.h"
#include "TresGimmickHitCountComponentOnTresAccumulationRecoveringSignatureDelegate.generated.h"

UDELEGATE(BlueprintCallable) DECLARE_DYNAMIC_MULTICAST_DELEGATE_OneParam(FTresGimmickHitCountComponentOnTresAccumulationRecoveringSignature, int32, HitCount);

